name: Spring Boot CI/CD Java21 Docker

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # 1️⃣ Checkout code
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # 2️⃣ Installer Java 21
      # =========================
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # =========================
      # 3️⃣ Build + Tests Maven
      # =========================
      - name: Build with Maven
        working-directory: Demo


      # =========================
      # 4️⃣ Login DockerHub
      # =========================
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # =========================
      # 5️⃣ Build image Docker
      # =========================
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_NAME }}/demo:latest .

      # =========================
      # 6️⃣ Push Docker image
      # =========================
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_NAME }}/demo:latest
