name: Spring Boot CI/CD Java21 Docker

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # 1️⃣ Checkout code
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # 2️⃣ Debug — voir la structure
      # =========================
      - name: Show folder structure
        run: ls -R

      # =========================
      # 3️⃣ Installer Java 21
      # =========================
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # =========================
      # 4️⃣ Build + Tests Maven
      # =========================
      - name: Build with Maven
        run: mvn clean verify

      # =========================
      # 5️⃣ Login DockerHub
      # =========================
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # =========================
      # 6️⃣ Build Docker image
      # =========================
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_NAME }}/demo:latest .

      # =========================
      # 7️⃣ Push Docker image
      # =========================
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_NAME }}/demo:latest
